# Generated by Django 4.1 on 2023-08-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaricularMaterias',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=17)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
