# Generated by Django 4.1 on 2023-08-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crearUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeusuario',
            name='contraseña',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registrodeusuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registrodeusuario',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
